// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace MyProject.Models;

public partial class TBrand
{
    public int FBrandId { get; set; }

    public string FBrandName { get; set; }
}