// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace MyProject.Models;

public partial class TCustomer
{
    public int FUserId { get; set; }

    public string FName { get; set; }

    public string FAccount { get; set; }

    public string FPwd { get; set; }

    public string FSalt { get; set; }

    public string FEmail { get; set; }

    public string FPhone { get; set; }

    public string FImgPath { get; set; }

    public bool FEnabled { get; set; }

    public virtual ICollection<TOrder> TOrders { get; set; } = new List<TOrder>();

    public virtual ICollection<TShoppingCart> TShoppingCarts { get; set; } = new List<TShoppingCart>();
}