// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace MyProject.Models;

public partial class TEmployee
{
    public int FEmployeeId { get; set; }

    public string FName { get; set; }

    public string FAccount { get; set; }

    public string FPassword { get; set; }

    public string FSalt { get; set; }

    public string FEmail { get; set; }
}