// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace MyProject.Models;

public partial class TOrderDetail
{
    public int FId { get; set; }

    public string FOrderId { get; set; }

    public int? FProductId { get; set; }

    public decimal? FSize { get; set; }

    public int? FQuantity { get; set; }

    public decimal? FUnitPrice { get; set; }

    public decimal? FSubTotal { get; set; }
}