// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace MyProject.Models;

public partial class TProduct
{
    public int FProductId { get; set; }

    public string FProductName { get; set; }

    public string FBrand { get; set; }

    public string FNumber { get; set; }

    public string FStyle { get; set; }

    public string FGender { get; set; }

    public string FMainColor { get; set; }

    public string FWidth { get; set; }

    public decimal? FPrice { get; set; }

    public string FImgPath { get; set; }

    public bool? FOnSale { get; set; }

    public string FNote { get; set; }

    public virtual ICollection<TShoppingCart> TShoppingCarts { get; set; } = new List<TShoppingCart>();

    public virtual ICollection<TSizeQty> TSizeQties { get; set; } = new List<TSizeQty>();
}