// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace MyProject.Models;

public partial class TShoppingCart
{
    public int FShopCartId { get; set; }

    public int? FCustomerId { get; set; }

    public int? FProductId { get; set; }

    public decimal? FSize { get; set; }

    public int? FQuantity { get; set; }

    public decimal? FUnitPrice { get; set; }

    public decimal? FSubtotal { get; set; }
}