// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace MyProject.Models;

public partial class VproductSizeQty
{
    public int 產品id { get; set; }

    public string 名稱 { get; set; }

    public string 品牌 { get; set; }

    public string 型號 { get; set; }

    public string 風格 { get; set; }

    public string 顏色 { get; set; }

    public string 性別 { get; set; }

    public decimal? 尺寸 { get; set; }

    public string 寬度 { get; set; }

    public decimal? 價格 { get; set; }

    public int? 庫存 { get; set; }

    public string 圖片 { get; set; }
}